"""
Seed Data for GAMEVERSE Platform.
Pre-populates 15 Topic categories, initial badges/achievements, and authentic challenge tasks.
"""

TOPICS_DATA = [   {   'color': '#3b82f6',
        'description': 'Core Python syntax, data structures, OOP, async programming, and standard library internals.',
        'icon': 'Terminal',
        'name': 'Python Programming',
        'order': 1,
        'slug': 'python'},
    {   'color': '#10b981',
        'description': 'Core programming paradigms, compilers, memory management, and software design principles.',
        'icon': 'Code',
        'name': 'Computer Science & Programming',
        'order': 2,
        'slug': 'programming'},
    {   'color': '#f59e0b',
        'description': 'Relational schema design, SQL joins, indexing, ACID transactions, and query optimization.',
        'icon': 'Database',
        'name': 'SQL & Relational Databases',
        'order': 3,
        'slug': 'sql'},
    {   'color': '#ec4899',
        'description': 'Frontend frameworks, DOM mechanics, HTTP/REST APIs, CSS Flexbox/Grid, and modern browser APIs.',
        'icon': 'Globe',
        'name': 'Modern Web Development',
        'order': 4,
        'slug': 'web-dev'},
    {   'color': '#ef4444',
        'description': 'Threat analysis, network defenses, cryptography, OWASP Top 10, and ethical hacking.',
        'icon': 'ShieldCheck',
        'name': 'Cybersecurity & Cryptography',
        'order': 5,
        'slug': 'cybersecurity'},
    {   'color': '#8b5cf6',
        'description': 'Probability, combinatorics, linear algebra, graph theory, and mathematical problem-solving.',
        'icon': 'Binary',
        'name': 'Mathematics & Discrete Math',
        'order': 6,
        'slug': 'mathematics'},
    {   'color': '#06b6d4',
        'description': 'Physics, chemistry, biology, astronomy, and fundamental scientific principles.',
        'icon': 'Atom',
        'name': 'Natural Sciences',
        'order': 7,
        'slug': 'science'},
    {   'color': '#64748b',
        'description': 'Trivia spanning world events, cultural milestones, arts, and global phenomena.',
        'icon': 'HelpCircle',
        'name': 'General Knowledge & Trivia',
        'order': 8,
        'slug': 'general-knowledge'},
    {   'color': '#14b8a6',
        'description': 'Deductive logic, pattern recognition, spatial reasoning, and brain teasers.',
        'icon': 'Cpu',
        'name': 'Logical Reasoning & Puzzles',
        'order': 9,
        'slug': 'logical-reasoning'},
    {   'color': '#f97316',
        'description': 'Data wrangling, statistical distributions, hypothesis testing, and BI visual storytelling.',
        'icon': 'BarChart3',
        'name': 'Data Analytics & Statistics',
        'order': 10,
        'slug': 'data-analytics'},
    {   'color': '#6366f1',
        'description': 'Neural networks, deep learning, NLP, transformers, reinforcement learning, and AI ethics.',
        'icon': 'Bot',
        'name': 'Artificial Intelligence & ML',
        'order': 11,
        'slug': 'ai-ml'},
    {   'color': '#0284c7',
        'description': 'TCP/IP suite, DNS, routing protocols, distributed cloud architecture, and CDN edge delivery.',
        'icon': 'Network',
        'name': 'Networking & Cloud Infrastructure',
        'order': 12,
        'slug': 'networking'},
    {   'color': '#d946ef',
        'description': 'Big-O complexity, binary search trees, dynamic programming, sorting, and graph traversals.',
        'icon': 'GitBranch',
        'name': 'Data Structures & Algorithms',
        'order': 13,
        'slug': 'algorithms'},
    {   'color': '#a855f7',
        'description': 'Ancient civilizations, global revolutions, empires, treaties, and turning points in human '
                       'history.',
        'icon': 'Landmark',
        'name': 'World History',
        'order': 14,
        'slug': 'history'},
    {   'color': '#84cc16',
        'description': 'Continents, capital cities, geopolitical borders, topographical features, and world landmarks.',
        'icon': 'Compass',
        'name': 'World Geography',
        'order': 15,
        'slug': 'geography'}]

ACHIEVEMENTS_DATA = [   {   'badge_color': '#3b82f6',
        'category': 'general',
        'code': 'FIRST_GAME',
        'description': 'Play and finish your very first game session in GameVerse.',
        'icon': 'Footprints',
        'requirement_type': 'games_played',
        'requirement_value': 1,
        'title': 'First Step',
        'xp_reward': 50},
    {   'badge_color': '#10b981',
        'category': 'general',
        'code': 'GAMES_10',
        'description': 'Complete 10 game sessions across any mode.',
        'icon': 'Medal',
        'requirement_type': 'games_played',
        'requirement_value': 10,
        'title': 'Regular Challenger',
        'xp_reward': 150},
    {   'badge_color': '#f59e0b',
        'category': 'general',
        'code': 'GAMES_50',
        'description': 'Complete 50 game sessions across any mode.',
        'icon': 'Trophy',
        'requirement_type': 'games_played',
        'requirement_value': 50,
        'title': 'Veteran Gamer',
        'xp_reward': 500},
    {   'badge_color': '#ec4899',
        'category': 'skill',
        'code': 'PERFECT_ROUND',
        'description': 'Finish a challenge round with 100% accuracy.',
        'icon': 'Sparkles',
        'requirement_type': 'perfect_game',
        'requirement_value': 1,
        'title': 'Flawless Execution',
        'xp_reward': 200},
    {   'badge_color': '#ef4444',
        'category': 'skill',
        'code': 'STREAK_5',
        'description': 'Reach a combo streak of 5 consecutive correct answers.',
        'icon': 'Flame',
        'requirement_type': 'streak',
        'requirement_value': 5,
        'title': 'On Fire',
        'xp_reward': 100},
    {   'badge_color': '#8b5cf6',
        'category': 'skill',
        'code': 'STREAK_10',
        'description': 'Reach a combo streak of 10 consecutive correct answers.',
        'icon': 'Zap',
        'requirement_type': 'streak',
        'requirement_value': 10,
        'title': 'Unstoppable',
        'xp_reward': 300},
    {   'badge_color': '#f97316',
        'category': 'score',
        'code': 'SCORE_1000',
        'description': 'Score over 1,000 points in a single match.',
        'icon': 'Target',
        'requirement_type': 'high_score',
        'requirement_value': 1000,
        'title': 'High Roller',
        'xp_reward': 250},
    {   'badge_color': '#eab308',
        'category': 'multiplayer',
        'code': 'MP_CHAMPION',
        'description': 'Win your first real-time multiplayer battle.',
        'icon': 'Crown',
        'requirement_type': 'win_multiplayer',
        'requirement_value': 1,
        'title': 'Arena Victor',
        'xp_reward': 300}]

TASKS_DATA = [   {   'answers': [   {   'is_correct': True,
                           'text': 'Lists are mutable and can be changed in-place, while tuples are immutable.'},
                       {'is_correct': False, 'text': 'Tuples are mutable, while lists are strictly immutable.'},
                       {'is_correct': False, 'text': 'Lists can only store numbers, while tuples store any type.'},
                       {'is_correct': False, 'text': 'Tuples cannot be indexed or sliced.'}],
        'difficulty': 'EASY',
        'explanation': 'Lists are mutable and can be changed in-place, while tuples are immutable.',
        'points': 10,
        'question': 'Which statement accurately describes the difference between a Python list and a Python tuple?',
        'tags': 'python,data-structures',
        'time_limit_seconds': 20,
        'title': 'List vs Tuple Mutability',
        'topic_slug': 'python'},
    {   'answers': [   {'is_correct': False, 'text': 'It accelerates CPU-bound multi-threaded loops automatically.'},
                       {   'is_correct': True,
                           'text': 'It prevents multiple threads from executing CPython bytecode simultaneously to '
                                   'protect memory integrity.'},
                       {'is_correct': False, 'text': 'It prevents garbage collection from freeing memory.'},
                       {   'is_correct': False,
                           'text': 'It forces all asynchronous coroutines to run on a single CPU core.'}],
        'difficulty': 'HARD',
        'explanation': 'The GIL prevents multiple native threads from executing Python bytecodes simultaneously to '
                       "protect CPython's memory management.",
        'points': 35,
        'question': 'What is the primary function of the GIL in CPython?',
        'tags': 'python,concurrency,gil',
        'time_limit_seconds': 25,
        'title': 'CPython Global Interpreter Lock',
        'topic_slug': 'python'},
    {   'answers': [   {'is_correct': False, 'text': 'Generators store elements on disk cache instead of RAM.'},
                       {'is_correct': False, 'text': 'List comprehensions convert numbers to strings.'},
                       {   'is_correct': True,
                           'text': 'Generators evaluate lazily on-demand rather than allocating memory for all '
                                   'elements upfront.'},
                       {'is_correct': False, 'text': 'Generators execute directly in GPU registers.'}],
        'difficulty': 'MEDIUM',
        'explanation': 'Generators evaluate lazily on-demand rather than allocating all elements in RAM upfront.',
        'points': 20,
        'question': 'Why is `(x*x for x in range(10**7))` more memory-efficient than `[x*x for x in range(10**7)]`?',
        'tags': 'python,generators,memory',
        'time_limit_seconds': 20,
        'title': 'Generator Memory Efficiency',
        'topic_slug': 'python'},
    {   'answers': [   {'is_correct': False, 'text': 'Dictionaries sort keys alphabetically automatically.'},
                       {'is_correct': False, 'text': 'Dictionaries randomize order for security.'},
                       {'is_correct': False, 'text': 'Dictionaries only retain order if using OrderedDict.'},
                       {'is_correct': True, 'text': 'Dictionaries are guaranteed to preserve insertion order.'}],
        'difficulty': 'EASY',
        'explanation': 'Dictionaries are officially guaranteed to preserve insertion order.',
        'points': 10,
        'question': 'Since Python 3.7+, what guarantee exists for standard `dict` keys?',
        'tags': 'python,dict,language-spec',
        'time_limit_seconds': 20,
        'title': 'Dictionary Key Insertion Order',
        'topic_slug': 'python'},
    {   'answers': [   {   'is_correct': True,
                           'text': 'It eliminates the default `__dict__` per instance, drastically saving memory '
                                   'overhead.'},
                       {'is_correct': False, 'text': 'It enables multithreaded lock-free execution for class methods.'},
                       {'is_correct': False, 'text': 'It compiles the class into C machine code.'},
                       {   'is_correct': False,
                           'text': 'It automatically serializes class instances to binary SQLite records.'}],
        'difficulty': 'EXPERT',
        'explanation': 'It eliminates the default instance __dict__, saving significant RAM when creating millions of '
                       'objects.',
        'points': 50,
        'question': 'What is the primary benefit of defining `__slots__` inside a class?',
        'tags': 'python,oop,optimization',
        'time_limit_seconds': 30,
        'title': 'Python __slots__ Optimization',
        'topic_slug': 'python'},
    {   'answers': [   {'is_correct': False, 'text': 'Only one single flat function.'},
                       {   'is_correct': True,
                           'text': 'Three levels of nested functions (factory, decorator, and wrapper).'},
                       {'is_correct': False, 'text': 'Exactly two functions.'},
                       {'is_correct': False, 'text': 'Four recursive functions.'}],
        'difficulty': 'MEDIUM',
        'explanation': 'A decorator accepting arguments requires an outer factory function, an inner decorator '
                       'function, and a wrapper function (3 levels).',
        'points': 20,
        'question': 'How many nested functions are typically required to implement a Python decorator that accepts '
                    'custom configuration arguments?',
        'tags': 'python,decorators,functions',
        'time_limit_seconds': 20,
        'title': 'Decorators with Arguments',
        'topic_slug': 'python'},
    {   'answers': [   {'is_correct': False, 'text': 'object'},
                       {'is_correct': False, 'text': 'ClassType'},
                       {'is_correct': True, 'text': 'type'},
                       {'is_correct': False, 'text': 'BaseMeta'}],
        'difficulty': 'HARD',
        'explanation': '`type` is the metaclass responsible for constructing class objects in Python.',
        'points': 35,
        'question': 'In Python, which built-in class is the default metaclass of all standard classes?',
        'tags': 'python,metaprogramming,oop',
        'time_limit_seconds': 25,
        'title': 'Python Metaclasses',
        'topic_slug': 'python'},
    {   'answers': [   {'is_correct': False, 'text': '__enter__'},
                       {'is_correct': False, 'text': '__close__'},
                       {'is_correct': False, 'text': '__catch__'},
                       {'is_correct': True, 'text': '__exit__'}],
        'difficulty': 'MEDIUM',
        'explanation': '`__exit__(exc_type, exc_val, exc_tb)` receives exception details and can suppress the '
                       'exception if it returns True.',
        'points': 20,
        'question': 'Which method of a Python context manager is invoked when an unhandled exception occurs inside a '
                    '`with` block?',
        'tags': 'python,context-manager,exceptions',
        'time_limit_seconds': 20,
        'title': 'Context Managers and __enter__/__exit__',
        'topic_slug': 'python'},
    {   'answers': [   {   'is_correct': True,
                           'text': 'It produces no side effects and always returns the same result for the same '
                                   'arguments.'},
                       {'is_correct': False, 'text': 'It only accepts integers as parameters.'},
                       {'is_correct': False, 'text': 'It is written in assembly or pure C.'},
                       {'is_correct': False, 'text': 'It executes in O(1) constant time.'}],
        'difficulty': 'EASY',
        'explanation': 'A pure function has no side effects and always returns identical output for identical inputs.',
        'points': 10,
        'question': "What characterizes a function as 'pure' in functional programming?",
        'tags': 'cs,functional,paradigms',
        'time_limit_seconds': 20,
        'title': 'Pure Function Definition',
        'topic_slug': 'programming'},
    {   'answers': [   {   'is_correct': False,
                           'text': 'Heap memory is allocated at compile time, while stack is dynamic.'},
                       {   'is_correct': True,
                           'text': 'Stack allocation is LIFO and managed automatically, while heap allocation is '
                                   'dynamic.'},
                       {'is_correct': False, 'text': 'Stack memory cannot overflow.'},
                       {'is_correct': False, 'text': 'Heap memory is faster than CPU cache registers.'}],
        'difficulty': 'MEDIUM',
        'explanation': 'Stack allocation is fast and strictly follows LIFO call frames, whereas heap allocation is '
                       'dynamic and managed manually or via garbage collection.',
        'points': 20,
        'question': 'How does stack memory allocation differ from heap memory allocation?',
        'tags': 'cs,memory,architecture',
        'time_limit_seconds': 20,
        'title': 'Stack vs Heap Allocation',
        'topic_slug': 'programming'},
    {   'answers': [   {'is_correct': False, 'text': 'A class should have only one reason to change.'},
                       {   'is_correct': False,
                           'text': 'Classes should be open for modification and closed for extension.'},
                       {   'is_correct': True,
                           'text': 'High-level modules should depend on abstractions rather than concrete low-level '
                                   'implementations.'},
                       {'is_correct': False, 'text': 'Interfaces must contain at least ten methods.'}],
        'difficulty': 'HARD',
        'explanation': 'High-level modules should depend upon abstractions rather than low-level concrete '
                       'implementations.',
        'points': 35,
        'question': 'What is the core directive of the Dependency Inversion Principle (SOLID)?',
        'tags': 'cs,solid,architecture',
        'time_limit_seconds': 25,
        'title': 'Dependency Inversion Principle',
        'topic_slug': 'programming'},
    {   'answers': [   {'is_correct': False, 'text': 'The API returns encrypted data on every request.'},
                       {'is_correct': False, 'text': 'The request is processed asynchronously in under 1ms.'},
                       {'is_correct': False, 'text': 'The endpoint requires two-factor authentication.'},
                       {   'is_correct': True,
                           'text': 'Executing the operation multiple times produces the exact same system state as '
                                   'executing it once.'}],
        'difficulty': 'MEDIUM',
        'explanation': 'Executing the operation multiple times leaves the system in the same state as executing it '
                       'once.',
        'points': 20,
        'question': 'What does it mean for an API operation to be idempotent?',
        'tags': 'cs,api,architecture',
        'time_limit_seconds': 20,
        'title': 'Idempotency in API Design',
        'topic_slug': 'programming'},
    {   'answers': [   {'is_correct': True, 'text': 'Preemptive Resource Reallocation'},
                       {'is_correct': False, 'text': 'Mutual Exclusion'},
                       {'is_correct': False, 'text': 'Hold and Wait'},
                       {'is_correct': False, 'text': 'Circular Wait'}],
        'difficulty': 'EXPERT',
        'explanation': 'The 4 Coffman conditions are Mutual Exclusion, Hold and Wait, No Preemption, and Circular '
                       'Wait. Preemptive Allocation prevents deadlock.',
        'points': 50,
        'question': "Which of the following is NOT one of Coffman's four conditions for a system deadlock to occur?",
        'tags': 'cs,concurrency,deadlock',
        'time_limit_seconds': 30,
        'title': 'Deadlock Coffman Conditions',
        'topic_slug': 'programming'},
    {   'answers': [   {'is_correct': False, 'text': 'INNER JOIN keeps all unmatched rows and drops matching rows.'},
                       {   'is_correct': True,
                           'text': 'LEFT JOIN keeps all rows from the left table, filling unmatched right columns with '
                                   'NULL.'},
                       {'is_correct': False, 'text': 'LEFT JOIN sorts results ascending by default.'},
                       {'is_correct': False, 'text': 'INNER JOIN only works on numeric primary keys.'}],
        'difficulty': 'EASY',
        'explanation': 'LEFT JOIN retains all rows from the left table with NULLs for unmatched right rows, while '
                       'INNER JOIN drops unmatched rows.',
        'points': 10,
        'question': 'What is the core difference between INNER JOIN and LEFT JOIN in SQL?',
        'tags': 'sql,joins,relational',
        'time_limit_seconds': 20,
        'title': 'INNER JOIN vs LEFT JOIN',
        'topic_slug': 'sql'},
    {   'answers': [   {'is_correct': False, 'text': 'O(1)'},
                       {'is_correct': False, 'text': 'O(N)'},
                       {'is_correct': True, 'text': 'O(log N)'},
                       {'is_correct': False, 'text': 'O(N log N)'}],
        'difficulty': 'MEDIUM',
        'explanation': 'A balanced B-Tree index has O(log N) search complexity.',
        'points': 20,
        'question': 'What is the standard time complexity for searching a key in a database B-Tree index?',
        'tags': 'sql,indexing,performance',
        'time_limit_seconds': 20,
        'title': 'B-Tree Index Search Complexity',
        'topic_slug': 'sql'},
    {   'answers': [   {'is_correct': False, 'text': 'READ COMMITTED'},
                       {'is_correct': False, 'text': 'READ UNCOMMITTED'},
                       {'is_correct': False, 'text': 'REPEATABLE READ'},
                       {'is_correct': True, 'text': 'SERIALIZABLE'}],
        'difficulty': 'HARD',
        'explanation': 'SERIALIZABLE prevents dirty reads, non-repeatable reads, and phantom reads through range '
                       'locking or snapshot isolation.',
        'points': 35,
        'question': 'Which ANSI SQL transaction isolation level completely prevents Phantom Reads?',
        'tags': 'sql,transactions,acid',
        'time_limit_seconds': 25,
        'title': 'ACID Isolation - Phantom Reads',
        'topic_slug': 'sql'},
    {   'answers': [   {'is_correct': True, 'text': 'OVER (PARTITION BY ...)'},
                       {'is_correct': False, 'text': 'GROUP BY ROLLUP'},
                       {'is_correct': False, 'text': 'HAVING COUNT(*)'},
                       {'is_correct': False, 'text': 'CROSS APPLY'}],
        'difficulty': 'MEDIUM',
        'explanation': 'OVER(PARTITION BY ...) calculates aggregate values across a window without collapsing '
                       'individual rows.',
        'points': 20,
        'question': 'Which SQL clause partitions rows for calculation without collapsing them like GROUP BY does?',
        'tags': 'sql,window-functions,analytics',
        'time_limit_seconds': 20,
        'title': 'SQL Window Functions',
        'topic_slug': 'sql'},
    {   'answers': [   {'is_correct': False, 'text': 'Every column must be an encrypted binary string.'},
                       {   'is_correct': True,
                           'text': 'It must be in 2NF and contain no transitive dependencies for non-key attributes.'},
                       {'is_correct': False, 'text': 'It must contain at least three foreign key relationships.'},
                       {'is_correct': False, 'text': 'All columns must have unique indexes.'}],
        'difficulty': 'HARD',
        'explanation': '3NF requires the table to be in 2NF and have no transitive functional dependencies on non-key '
                       'attributes.',
        'points': 35,
        'question': 'What is required for a database table to be in Third Normal Form (3NF)?',
        'tags': 'sql,database-design,normalization',
        'time_limit_seconds': 25,
        'title': 'Database Normalization - 3NF',
        'topic_slug': 'sql'},
    {   'answers': [   {'is_correct': False, 'text': 'Transpiling JSX directly into browser assembly code.'},
                       {'is_correct': False, 'text': 'Managing session authentication tokens automatically.'},
                       {   'is_correct': True,
                           'text': 'Diffing Virtual DOM trees to compute the minimal set of real DOM mutations.'},
                       {'is_correct': False, 'text': 'Optimizing network roundtrips via WebRTC.'}],
        'difficulty': 'MEDIUM',
        'explanation': 'Reconciliation compares new and old virtual trees to apply minimal real DOM patches.',
        'points': 20,
        'question': 'What is the purpose of reconciliation in React?',
        'tags': 'react,frontend,virtual-dom',
        'time_limit_seconds': 20,
        'title': 'React Virtual DOM Reconciliation',
        'topic_slug': 'web-dev'},
    {   'answers': [   {'is_correct': False, 'text': 'justify-content'},
                       {'is_correct': False, 'text': 'flex-direction'},
                       {'is_correct': False, 'text': 'align-content'},
                       {'is_correct': True, 'text': 'align-items'}],
        'difficulty': 'EASY',
        'explanation': 'align-items aligns items on the cross axis, while justify-content aligns on the main axis.',
        'points': 10,
        'question': 'Which CSS property aligns items along the cross axis in a row flex container?',
        'tags': 'css,flexbox,layout',
        'time_limit_seconds': 20,
        'title': 'CSS Flexbox Axis Alignment',
        'topic_slug': 'web-dev'},
    {   'answers': [   {'is_correct': True, 'text': 'OPTIONS'},
                       {'is_correct': False, 'text': 'HEAD'},
                       {'is_correct': False, 'text': 'GET'},
                       {'is_correct': False, 'text': 'PATCH'}],
        'difficulty': 'MEDIUM',
        'explanation': 'Browsers automatically send an HTTP OPTIONS request to verify CORS headers prior to sending '
                       'complex requests.',
        'points': 20,
        'question': 'Which HTTP method is sent by web browsers for a CORS preflight check?',
        'tags': 'http,cors,security',
        'time_limit_seconds': 20,
        'title': 'CORS Preflight Request',
        'topic_slug': 'web-dev'},
    {   'answers': [   {   'is_correct': False,
                           'text': 'It replaces all asynchronous Promises with synchronous operations.'},
                       {   'is_correct': True,
                           'text': 'It memoizes function instances between renders to prevent unnecessary child '
                                   're-renders.'},
                       {'is_correct': False, 'text': 'It prevents component state from persisting in memory.'},
                       {'is_correct': False, 'text': 'It forces immediate DOM repainting.'}],
        'difficulty': 'MEDIUM',
        'explanation': 'useCallback memoizes callback function instances across renders to prevent unnecessary '
                       're-rendering of child components.',
        'points': 20,
        'question': 'What problem does the `useCallback` hook solve in React?',
        'tags': 'react,hooks,performance',
        'time_limit_seconds': 20,
        'title': 'React useCallback Purpose',
        'topic_slug': 'web-dev'},
    {   'answers': [   {'is_correct': False, 'text': 'Client-side regex validation on input boxes.'},
                       {'is_correct': False, 'text': 'Base64 encoding all user input strings.'},
                       {   'is_correct': True,
                           'text': 'Using parameterized queries / prepared statements with database drivers or ORMs.'},
                       {'is_correct': False, 'text': 'Enabling SSL certificates on the load balancer.'}],
        'difficulty': 'EASY',
        'explanation': 'Parameterized queries (prepared statements) ensure user input is treated as data parameters '
                       'rather than executable SQL code.',
        'points': 10,
        'question': 'What is the most effective defense against SQL injection attacks?',
        'tags': 'security,sqli,owasp',
        'time_limit_seconds': 20,
        'title': 'SQL Injection Primary Defense',
        'topic_slug': 'cybersecurity'},
    {   'answers': [   {'is_correct': False, 'text': 'RSA'},
                       {'is_correct': False, 'text': 'Elliptic Curve Cryptography (ECC)'},
                       {'is_correct': False, 'text': 'Diffie-Hellman'},
                       {'is_correct': True, 'text': 'AES (Advanced Encryption Standard)'}],
        'difficulty': 'MEDIUM',
        'explanation': 'AES is a symmetric block cipher, while RSA and ECC are asymmetric public-key systems.',
        'points': 20,
        'question': 'Which of the following is a symmetric key encryption standard?',
        'tags': 'security,cryptography,aes',
        'time_limit_seconds': 20,
        'title': 'Symmetric vs Asymmetric Encryption',
        'topic_slug': 'cybersecurity'},
    {   'answers': [   {   'is_correct': True,
                           'text': 'By restricting the allowed sources and execution domains for executable scripts '
                                   'and media.'},
                       {'is_correct': False, 'text': "By encrypting the user's password in browser memory."},
                       {'is_correct': False, 'text': 'By banning all JavaScript from running on the page.'},
                       {'is_correct': False, 'text': 'By converting all cookies into HTTP-only session headers.'}],
        'difficulty': 'HARD',
        'explanation': 'CSP restricts the origins from which scripts, styles, and other assets can be loaded and '
                       'executed by the browser.',
        'points': 35,
        'question': 'How does the `Content-Security-Policy` HTTP header mitigate Cross-Site Scripting (XSS)?',
        'tags': 'security,xss,csp,headers',
        'time_limit_seconds': 25,
        'title': 'Content Security Policy (CSP)',
        'topic_slug': 'cybersecurity'},
    {   'answers': [   {'is_correct': False, 'text': '60'},
                       {'is_correct': True, 'text': '120'},
                       {'is_correct': False, 'text': '25'},
                       {'is_correct': False, 'text': '720'}],
        'difficulty': 'EASY',
        'explanation': '5! = 5 * 4 * 3 * 2 * 1 = 120.',
        'points': 10,
        'question': 'How many distinct permutations exist for arranging 5 books on a shelf?',
        'tags': 'math,combinatorics,factorial',
        'time_limit_seconds': 20,
        'title': 'Combinatorics Factorial',
        'topic_slug': 'mathematics'},
    {   'answers': [   {'is_correct': False, 'text': 'det(A) + det(B)'},
                       {'is_correct': False, 'text': 'det(A) / det(B)'},
                       {'is_correct': True, 'text': 'det(A) * det(B)'},
                       {'is_correct': False, 'text': 'det(A + B)'}],
        'difficulty': 'MEDIUM',
        'explanation': 'det(AB) = det(A) * det(B).',
        'points': 20,
        'question': 'For square matrices A and B of identical size, what is det(A * B)?',
        'tags': 'math,linear-algebra,matrices',
        'time_limit_seconds': 20,
        'title': 'Matrix Multiplication Determinant',
        'topic_slug': 'mathematics'},
    {   'answers': [   {'is_correct': False, 'text': 'All vertices must have odd degree'},
                       {'is_correct': False, 'text': 'Exactly 1 vertex with odd degree'},
                       {'is_correct': False, 'text': 'Every vertex must have even degree with prime index'},
                       {'is_correct': True, 'text': 'Exactly 0 or 2 vertices with odd degree'}],
        'difficulty': 'HARD',
        'explanation': 'Euler proved a graph has an Eulerian path if and only if exactly 0 or 2 vertices have odd '
                       'degree.',
        'points': 35,
        'question': 'A connected graph has an Eulerian path if and only if it has how many vertices of odd degree?',
        'tags': 'math,graph-theory,euler',
        'time_limit_seconds': 25,
        'title': 'Eulerian Path Condition',
        'topic_slug': 'mathematics'},
    {   'answers': [   {'is_correct': True, 'text': '300,000 km/s (3 x 10^8 m/s)'},
                       {'is_correct': False, 'text': '150,000 km/s (1.5 x 10^8 m/s)'},
                       {'is_correct': False, 'text': '3,000,000 km/s (3 x 10^9 m/s)'},
                       {'is_correct': False, 'text': '30,000 km/s (3 x 10^7 m/s)'}],
        'difficulty': 'EASY',
        'explanation': 'The speed of light in a vacuum is 299,792,458 m/s (approx 3 x 10^8 m/s).',
        'points': 10,
        'question': 'What is the approximate speed of light in a vacuum ($c$)?',
        'tags': 'science,physics,constants',
        'time_limit_seconds': 20,
        'title': 'Speed of Light in Vacuum',
        'topic_slug': 'science'},
    {   'answers': [   {'is_correct': False, 'text': 'DNA'},
                       {'is_correct': True, 'text': 'ATP (Adenosine Triphosphate)'},
                       {'is_correct': False, 'text': 'Hemoglobin'},
                       {'is_correct': False, 'text': 'Sucrose'}],
        'difficulty': 'EASY',
        'explanation': 'Mitochondria produce ATP (Adenosine Triphosphate) through oxidative phosphorylation.',
        'points': 10,
        'question': 'Which molecule is the primary chemical energy currency generated in mitochondria?',
        'tags': 'science,biology,energy',
        'time_limit_seconds': 20,
        'title': 'Cellular Energy Production',
        'topic_slug': 'science'},
    {   'answers': [   {'is_correct': False, 'text': '1965'},
                       {'is_correct': False, 'text': '1971'},
                       {'is_correct': True, 'text': '1969'},
                       {'is_correct': False, 'text': '1958'}],
        'difficulty': 'EASY',
        'explanation': 'Apollo 11 landed on the Moon on July 20, 1969.',
        'points': 10,
        'question': 'In which year did the Apollo 11 mission land humans on the Moon?',
        'tags': 'trivia,history,space',
        'time_limit_seconds': 20,
        'title': 'Apollo 11 Moon Landing Year',
        'topic_slug': 'general-knowledge'},
    {   'answers': [   {'is_correct': False, 'text': 'Copper (Cu)'},
                       {'is_correct': False, 'text': 'Gold (Au)'},
                       {'is_correct': False, 'text': 'Platinum (Pt)'},
                       {'is_correct': True, 'text': 'Silver (Ag)'}],
        'difficulty': 'MEDIUM',
        'explanation': 'Silver (Ag) has the highest electrical and thermal conductivity of any known metal.',
        'points': 20,
        'question': 'Which chemical element is the most electrically conductive metal at standard temperature?',
        'tags': 'trivia,science,elements',
        'time_limit_seconds': 20,
        'title': 'Most Electrically Conductive Metal',
        'topic_slug': 'general-knowledge'},
    {   'answers': [   {'is_correct': True, 'text': 'If not Q, then not P'},
                       {'is_correct': False, 'text': 'If not P, then not Q'},
                       {'is_correct': False, 'text': 'If Q, then P'},
                       {'is_correct': False, 'text': 'P and not Q'}],
        'difficulty': 'MEDIUM',
        'explanation': "The contrapositive of 'P -> Q' is 'not Q -> not P', which is strictly logically equivalent.",
        'points': 20,
        'question': "What is the contrapositive of the statement 'If P, then Q'?",
        'tags': 'logic,reasoning,deduction',
        'time_limit_seconds': 20,
        'title': 'Contrapositive Equivalence',
        'topic_slug': 'logical-reasoning'},
    {   'answers': [   {'is_correct': False, 'text': '54'},
                       {'is_correct': True, 'text': '56'},
                       {'is_correct': False, 'text': '60'},
                       {'is_correct': False, 'text': '48'}],
        'difficulty': 'MEDIUM',
        'explanation': 'Differences are +4, +6, +8, +10, +12, so next is +14 => 42 + 14 = 56.',
        'points': 20,
        'question': 'What is the next number in the pattern: 2, 6, 12, 20, 30, 42, __?',
        'tags': 'logic,sequences,patterns',
        'time_limit_seconds': 20,
        'title': 'Sequence Pattern',
        'topic_slug': 'logical-reasoning'},
    {   'answers': [   {'is_correct': False, 'text': 'Variance is the square root of standard deviation.'},
                       {'is_correct': False, 'text': 'Standard deviation equals variance times sample size.'},
                       {'is_correct': True, 'text': 'Standard deviation is the square root of variance.'},
                       {'is_correct': False, 'text': 'They are unrelated measures.'}],
        'difficulty': 'EASY',
        'explanation': 'Standard deviation is the square root of variance.',
        'points': 10,
        'question': 'What is the mathematical connection between standard deviation and variance?',
        'tags': 'statistics,analytics,variance',
        'time_limit_seconds': 20,
        'title': 'Variance and Standard Deviation',
        'topic_slug': 'data-analytics'},
    {   'answers': [   {'is_correct': False, 'text': 'Failing to reject a false null hypothesis (false negative).'},
                       {'is_correct': False, 'text': 'Collecting an unrepresentative sample size.'},
                       {'is_correct': False, 'text': 'Using the wrong regression formula.'},
                       {'is_correct': True, 'text': 'Rejecting a true null hypothesis (false positive).'}],
        'difficulty': 'HARD',
        'explanation': 'A Type I error is rejecting a true null hypothesis (false positive).',
        'points': 35,
        'question': 'What constitutes a Type I error in statistical hypothesis testing?',
        'tags': 'statistics,hypothesis-testing,errors',
        'time_limit_seconds': 25,
        'title': 'Type I Error in Statistics',
        'topic_slug': 'data-analytics'},
    {   'answers': [   {'is_correct': True, 'text': 'softmax((Q * K^T) / sqrt(d_k)) * V'},
                       {'is_correct': False, 'text': 'sigmoid(Q * K) * V^T'},
                       {'is_correct': False, 'text': 'ReLU(Q + K) * V'},
                       {'is_correct': False, 'text': 'tanh(Q * V^T) * K'}],
        'difficulty': 'HARD',
        'explanation': 'Attention(Q, K, V) = softmax(Q*K^T / sqrt(d_k)) * V.',
        'points': 35,
        'question': 'What formula calculates Scaled Dot-Product Attention in Transformers?',
        'tags': 'ai,transformers,deep-learning',
        'time_limit_seconds': 25,
        'title': 'Transformer Self-Attention',
        'topic_slug': 'ai-ml'},
    {   'answers': [   {'is_correct': False, 'text': 'Increasing learning rates exponentially during backpropagation.'},
                       {   'is_correct': True,
                           'text': 'Randomly disabling neuron activations during training to combat overfitting.'},
                       {'is_correct': False, 'text': 'Compressing weights into 8-bit integers for deployment.'},
                       {'is_correct': False, 'text': 'Converting continuous loss values to discrete integers.'}],
        'difficulty': 'EASY',
        'explanation': 'Dropout randomly deactivates neurons during training to prevent co-adaptation and overfitting.',
        'points': 10,
        'question': 'What is the purpose of Dropout in neural networks?',
        'tags': 'ai,regularization,dropout',
        'time_limit_seconds': 20,
        'title': 'Neural Network Dropout',
        'topic_slug': 'ai-ml'},
    {   'answers': [   {'is_correct': False, 'text': 'ACK -> SYN -> FIN'},
                       {'is_correct': False, 'text': 'HELLO -> READY -> CONNECT'},
                       {'is_correct': True, 'text': 'SYN -> SYN-ACK -> ACK'},
                       {'is_correct': False, 'text': 'PING -> PONG -> ACK'}],
        'difficulty': 'EASY',
        'explanation': 'SYN -> SYN-ACK -> ACK.',
        'points': 10,
        'question': 'What is the correct order of packets for establishing a TCP handshake?',
        'tags': 'networking,tcp,protocols',
        'time_limit_seconds': 20,
        'title': 'TCP 3-Way Handshake',
        'topic_slug': 'networking'},
    {   'answers': [   {'is_correct': False, 'text': 'IPv4 address'},
                       {'is_correct': False, 'text': 'Mail server hostname'},
                       {'is_correct': False, 'text': 'Canonical alias'},
                       {'is_correct': True, 'text': 'IPv6 address'}],
        'difficulty': 'EASY',
        'explanation': 'AAAA records map a domain name to an IPv6 address.',
        'points': 10,
        'question': 'What address type does a DNS AAAA record point to?',
        'tags': 'networking,dns,ipv6',
        'time_limit_seconds': 20,
        'title': 'DNS AAAA Record',
        'topic_slug': 'networking'},
    {   'answers': [   {'is_correct': True, 'text': 'O(log N)'},
                       {'is_correct': False, 'text': 'O(N)'},
                       {'is_correct': False, 'text': 'O(1)'},
                       {'is_correct': False, 'text': 'O(N^2)'}],
        'difficulty': 'EASY',
        'explanation': 'Binary search divides search space by half at each step, yielding O(log N).',
        'points': 10,
        'question': 'What is the worst-case time complexity of Binary Search on a sorted array?',
        'tags': 'algorithms,binary-search,complexity',
        'time_limit_seconds': 20,
        'title': 'Binary Search Complexity',
        'topic_slug': 'algorithms'},
    {   'answers': [   {'is_correct': False, 'text': 'The graph must be a Directed Acyclic Graph (DAG).'},
                       {'is_correct': True, 'text': 'All edge weights must be non-negative (>= 0).'},
                       {'is_correct': False, 'text': 'The graph must contain no cycles.'},
                       {'is_correct': False, 'text': 'Edge weights must be powers of 2.'}],
        'difficulty': 'HARD',
        'explanation': 'All edge weights must be non-negative (>= 0). If negative weights exist, Bellman-Ford must be '
                       'used.',
        'points': 35,
        'question': "What fundamental requirement must graph edge weights satisfy in Dijkstra's algorithm?",
        'tags': 'algorithms,graphs,dijkstra',
        'time_limit_seconds': 25,
        'title': 'Dijkstra Algorithm Constraint',
        'topic_slug': 'algorithms'},
    {   'answers': [   {'is_correct': False, 'text': '1066'},
                       {'is_correct': False, 'text': '1492'},
                       {'is_correct': True, 'text': '1215'},
                       {'is_correct': False, 'text': '1776'}],
        'difficulty': 'MEDIUM',
        'explanation': 'The Magna Carta was signed in 1215 at Runnymede.',
        'points': 20,
        'question': 'In which year was the Magna Carta signed by King John of England?',
        'tags': 'history,medieval,england',
        'time_limit_seconds': 20,
        'title': 'Magna Carta Year',
        'topic_slug': 'history'},
    {   'answers': [   {'is_correct': False, 'text': 'Amazon River'},
                       {'is_correct': False, 'text': 'Yangtze River'},
                       {'is_correct': False, 'text': 'Mississippi River'},
                       {'is_correct': True, 'text': 'Nile River'}],
        'difficulty': 'EASY',
        'explanation': 'The Nile River in Africa flows approximately 6,650 km.',
        'points': 10,
        'question': 'Which river is traditionally recognized as the longest in the world?',
        'tags': 'geography,rivers,africa',
        'time_limit_seconds': 20,
        'title': 'Longest River in the World',
        'topic_slug': 'geography'},
    {   'answers': [   {'is_correct': True, 'text': 'Challenger Deep'},
                       {'is_correct': False, 'text': 'Java Trench'},
                       {'is_correct': False, 'text': 'Puerto Rico Trench'},
                       {'is_correct': False, 'text': 'Milwaukee Deep'}],
        'difficulty': 'MEDIUM',
        'explanation': 'Challenger Deep in the Mariana Trench descends to approximately 10,994 meters.',
        'points': 20,
        'question': "What is the deepest known location in Earth's oceans?",
        'tags': 'geography,oceans,earth',
        'time_limit_seconds': 20,
        'title': 'Deepest Oceanic Point',
        'topic_slug': 'geography'}]
